= Installation
:description: Install the Stackable Druid Operator and its dependencies on Kubernetes using stackablectl or Helm.

Install the Stackable Operator for Apache Druid and operators for its dependencies -- ZooKeeper and HDFS -- as well as the commons, secret and listener operator which are required by all Stackable operators.

There are multiple ways to install the operators, xref:management:stackablectl:index.adoc[] is the preferred way but Helm is also supported.
OpenShift users may prefer installing the operator from the RedHat Certified Operator catalog using the OpenShift web console.

[tabs]
====
stackablectl::
+
--
stackablectl is the command line tool to interact with Stackable operators and the recommended way to install operators.
Follow the xref:management:stackablectl:installation.adoc[installation steps] for your platform.

After you have installed stackablectl run the following command to install all Operators necessary for Druid:

[source,bash]
----
include::example$getting_started/getting_started.sh[tag=stackablectl-install-operators]
----

The tool prints

[source]
include::example$getting_started/install_output.txt[]

TIP: Consult the xref:management:stackablectl:quickstart.adoc[] to learn more about how to use `stackablectl`.
--

Helm::
+
--
You can also use Helm to install the operators.

.Add the Stackable Helm repository
[source,bash]
----
include::example$getting_started/getting_started.sh[tag=helm-add-repo]
----

.Install the Stackable operators
[source,bash]
----
include::example$getting_started/getting_started.sh[tag=helm-install-operators]
----

Helm deploys the operators in a Kubernetes Deployment and applies the CRDs for the Apache Druid service (as well as the CRDs for the required operators).
--
====

== What's next

xref:getting_started/first_steps.adoc[Set up a Druid cluster] and its dependencies and
xref:getting_started/first_steps.adoc#_ingest_example_data[ingest example data] and
xref:getting_started/first_steps.adoc#_query_the_data[query the data].
