---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: druid-operator-deployment
  labels:
    app.kubernetes.io/name: druid-operator
    app.kubernetes.io/instance: druid-operator
    app.kubernetes.io/version: "0.7.0"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: druid-operator
      app.kubernetes.io/instance: druid-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: druid-operator
        app.kubernetes.io/instance: druid-operator
    spec:
      serviceAccountName: druid-operator-serviceaccount
      securityContext: {}
      containers:
        - name: druid-operator
          securityContext: {}
          image: "docker.stackable.tech/stackable/druid-operator:0.7.0"
          imagePullPolicy: IfNotPresent
          resources: {}
          volumeMounts:
            - mountPath: /etc/stackable/druid-operator/config-spec
              name: config-spec
      volumes:
        - name: config-spec
          configMap:
            name: druid-operator-configmap
