---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: druid-operator-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - secrets
      - services
      - endpoints
      - serviceaccounts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - create
      - delete
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - druid.stackable.tech
    resources:
      - druidclusters
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - druid.stackable.tech
    resources:
      - druidclusters/status
    verbs:
      - patch
  - apiGroups:
      - s3.stackable.tech
    resources:
      - s3connections
      - s3buckets
    verbs:
      - get
      - list
      - watch
