apiVersion: v1
kind: Service
metadata:
  name: druid-router
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: druid
    app.kubernetes.io/component: router
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30888
