---
apiVersion: druid.stackable.tech/v1alpha1
kind: DruidCluster
metadata:
  name: simple-druid
spec:
  image:
    productVersion: 33.0.0
  clusterConfig:
    zookeeperConfigMapName: simple-druid-znode
    deepStorage:
      hdfs:
        configMapName: simple-hdfs
        directory: /druid
    metadataStorageDatabase:
      dbType: postgresql
      connString: jdbc:postgresql://postgresql-druid/druid
      host: postgresql-druid
      port: 5432
      credentialsSecret: druid-db-credentials
  brokers:
    roleGroups:
      default:
        replicas: 1
    roleConfig:
      listenerClass: external-stable # This exposes this role outside of Kubernetes. Remove this configuration if this is not desired
  coordinators:
    roleGroups:
      default:
        replicas: 1
    roleConfig:
      listenerClass: external-stable # This exposes this role outside of Kubernetes. Remove this configuration if this is not desired
  historicals:
    roleGroups:
      default:
        replicas: 1
  middleManagers:
    roleGroups:
      default:
        replicas: 1
  routers:
    roleGroups:
      default:
        replicas: 1
    roleConfig:
      listenerClass: external-stable # This exposes this role outside of Kubernetes. Remove this configuration if this is not desired
---
apiVersion: v1
kind: Secret
metadata:
  name: druid-db-credentials
stringData:
  username: druid
  password: druid
