version: 0.1.0
spec:
  units:
    - unit: &unitDirectory
        name: "directory"
        regex: "^/|(/[\\w-]+)+$"
        examples:
          - "/tmp/xyz"

###################################################################################################
# runtime.properties
###################################################################################################

properties:

  - property: &plaintext
      propertyNames:
        - name: "druid.plaintext"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "integer"
      roles:
        - name: "broker"
          required: true
        - name: "coordinator"
          required: true
        - name: "historical"
          required: true
        - name: "middleManager"
          required: true
        - name: "router"
          required: true
      asOfVersion: "0.0.0"

  - property: &startupLoggingLogProperties
      propertyNames:
        - name: "druid.startup.logging.logProperties"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "bool"
      defaultValues:
        - fromVersion: "0.0.0"
          value: "true"
      roles:
        - name: "broker"
          required: true
        - name: "coordinator"
          required: true
        - name: "historical"
          required: true
        - name: "middleManager"
          required: true
        - name: "router"
          required: true
      asOfVersion: "0.0.0"

  - property: &monitoringMonitors
      propertyNames:
        - name: "druid.monitoring.monitors"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "string"
      defaultValues:
        - fromVersion: "0.0.0"
          value: "[\"org.apache.druid.java.util.metrics.JvmMonitor\"]"
      roles:
        - name: "broker"
          required: true
        - name: "coordinator"
          required: true
        - name: "historical"
          required: true
        - name: "middleManager"
          required: true
        - name: "router"
          required: true
      asOfVersion: "0.0.0"

  - property: &emitter
      propertyNames:
        - name: "druid.emitter"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "string"
      defaultValues:
        - fromVersion: "0.0.0"
          value: "prometheus"
      roles:
        - name: "broker"
          required: true
        - name: "coordinator"
          required: true
        - name: "historical"
          required: true
        - name: "middleManager"
          required: true
        - name: "router"
          required: true
      asOfVersion: "0.0.0"

  - property: &emitterPrometheusStrategy
      propertyNames:
        - name: "druid.emitter.prometheus.strategy"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "string"
      defaultValues:
        - fromVersion: "0.0.0"
          value: "exporter"
      roles:
        - name: "broker"
          required: true
        - name: "coordinator"
          required: true
        - name: "historical"
          required: true
        - name: "middleManager"
          required: true
        - name: "router"
          required: true
      asOfVersion: "0.0.0"

  - property: &emitterPrometheusNamespace
      propertyNames:
        - name: "druid.emitter.prometheus.namespace"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "string"
      defaultValues:
        - fromVersion: "0.0.0"
          value: "druid"
      roles:
        - name: "broker"
          required: true
        - name: "coordinator"
          required: true
        - name: "historical"
          required: true
        - name: "middleManager"
          required: true
        - name: "router"
          required: true
      asOfVersion: "0.0.0"

  - property: &emitterPrometheusPort
      propertyNames:
        - name: "druid.emitter.prometheus.port"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "integer"
      roles:
        - name: "broker"
          required: true
        - name: "coordinator"
          required: true
        - name: "historical"
          required: true
        - name: "middleManager"
          required: true
        - name: "router"
          required: true
      asOfVersion: "0.0.0"

  - property: &metadataStorageType
      propertyNames:
        - name: "druid.metadata.storage.type"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "string"
      roles:
        - name: "broker"
          required: true
        - name: "coordinator"
          required: true
        - name: "historical"
          required: true
        - name: "middleManager"
          required: true
        - name: "router"
          required: true
      asOfVersion: "0.0.0"

  - property: &metadataStorageConnectURI
      propertyNames:
        - name: "druid.metadata.storage.connector.connectURI"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "string"
      roles:
        - name: "broker"
          required: true
        - name: "coordinator"
          required: true
        - name: "historical"
          required: true
        - name: "middleManager"
          required: true
        - name: "router"
          required: true
      asOfVersion: "0.0.0"

  - property: &metadataStorageHost
      propertyNames:
        - name: "druid.metadata.storage.connector.host"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "string"
      roles:
        - name: "broker"
          required: true
        - name: "coordinator"
          required: true
        - name: "historical"
          required: true
        - name: "middleManager"
          required: true
        - name: "router"
          required: true
      asOfVersion: "0.0.0"

  - property: &metadataStoragePort
      propertyNames:
        - name: "druid.metadata.storage.connector.port"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "integer"
        min: "1024"
        max: "65535"
      roles:
        - name: "broker"
          required: true
        - name: "coordinator"
          required: true
        - name: "historical"
          required: true
        - name: "middleManager"
          required: true
        - name: "router"
          required: true
      asOfVersion: "0.0.0"

  - property: &metadataStorageUser
      propertyNames:
        - name: "druid.metadata.storage.connector.user"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "string"
      roles:
        - name: "broker"
          required: false
        - name: "coordinator"
          required: false
        - name: "historical"
          required: false
        - name: "middleManager"
          required: false
        - name: "router"
          required: false
      asOfVersion: "0.0.0"

  - property: &metadataStoragePassword
      propertyNames:
        - name: "druid.metadata.storage.connector.password"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "string"
      roles:
        - name: "broker"
          required: false
        - name: "coordinator"
          required: false
        - name: "historical"
          required: false
        - name: "middleManager"
          required: false
        - name: "router"
          required: false
      asOfVersion: "0.0.0"

  - property: &indexerLogsDirectory
      propertyNames:
        - name: "druid.indexer.logs.directory"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "string"
      defaultValues:
        - fromVersion: "0.0.0"
          value: "/stackable/var/druid/indexing-logs"
      roles:
        - name: "broker"
          required: true
        - name: "coordinator"
          required: true
        - name: "historical"
          required: true
        - name: "middleManager"
          required: true
        - name: "router"
          required: true
      asOfVersion: "0.0.0"

  - property: &processingTmpDir
      propertyNames:
        - name: "druid.processing.tmpDir"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "string"
      defaultValues:
        - fromVersion: "0.0.0"
          value: "/stackable/var/druid/processing"
      roles:
        - name: "broker"
          required: true
        - name: "coordinator"
          required: false
        - name: "historical"
          required: true
        - name: "middleManager"
          required: false
        - name: "router"
          required: false
      asOfVersion: "0.0.0"

  - property: &indexerTaskHadoopWorkingPath
      propertyNames:
        - name: "druid.indexer.task.hadoopWorkingPath"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "string"
      defaultValues:
        - fromVersion: "0.0.0"
          value: "/stackable/var/druid/hadoop-tmp"
      roles:
        - name: "broker"
          required: false
        - name: "coordinator"
          required: false
        - name: "historical"
          required: false
        - name: "middleManager"
          required: true
        - name: "router"
          required: false
      asOfVersion: "0.0.0"

  - property: &indexerTaskBaseTaskDir
      propertyNames:
        - name: "druid.indexer.task.baseTaskDir"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "string"
      defaultValues:
        - fromVersion: "0.0.0"
          value: "/stackable/var/druid/task"
      roles:
        - name: "broker"
          required: false
        - name: "coordinator"
          required: false
        - name: "historical"
          required: false
        - name: "middleManager"
          required: true
        - name: "router"
          required: false
      asOfVersion: "0.0.0"

  - property: &indexerRunnerJavaOpts
      propertyNames:
        - name: "druid.indexer.runner.javaOpts"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "string"
      defaultValues:
        - fromVersion: "0.0.0"
          value: "-server -Xms256m -Xmx256m -XX:MaxDirectMemorySize=300m -Duser.timezone=UTC -Dfile.encoding=UTF-8 -XX:+ExitOnOutOfMemoryError -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager"
      roles:
        - name: "broker"
          required: false
        - name: "coordinator"
          required: false
        - name: "historical"
          required: false
        - name: "middleManager"
          required: true
        - name: "router"
          required: false
      asOfVersion: "0.0.0"

  - property: &routerManagementProxyEnabled
      propertyNames:
        # Management proxy to coordinator / overlord: required for unified web console.
        - name: "druid.router.managementProxy.enabled"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "bool"
      defaultValues:
        - fromVersion: "0.0.0"
          value: "true"
      roles:
        - name: "broker"
          required: false
        - name: "coordinator"
          required: false
        - name: "historical"
          required: false
        - name: "middleManager"
          required: false
        - name: "router"
          required: true
      asOfVersion: "0.0.0"

  - property: &routerHttpNumConnections
      propertyNames:
        - name: "druid.router.http.numConnections"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "integer"
      defaultValues:
        - fromVersion: "0.0.0"
          value: "25"
      roles:
        - name: "broker"
          required: false
        - name: "coordinator"
          required: false
        - name: "historical"
          required: false
        - name: "middleManager"
          required: false
        - name: "router"
          required: true
      asOfVersion: "0.0.0"

  - property: &historicalCacheUseCache
      propertyNames:
        - name: "druid.historical.cache.useCache"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "bool"
      defaultValues:
        - fromVersion: "0.0.0"
          value: "true"
      roles:
        - name: "broker"
          required: false
        - name: "coordinator"
          required: false
        - name: "historical"
          required: true
        - name: "middleManager"
          required: false
        - name: "router"
          required: false
      asOfVersion: "0.0.0"

  - property: &historicalCachePopulateCache
      propertyNames:
        - name: "druid.historical.cache.populateCache"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "bool"
      defaultValues:
        - fromVersion: "0.0.0"
          value: "true"
      roles:
        - name: "broker"
          required: false
        - name: "coordinator"
          required: false
        - name: "historical"
          required: true
        - name: "middleManager"
          required: false
        - name: "router"
          required: false
      asOfVersion: "0.0.0"

  - property: &coordinatorStartDelay
      propertyNames:
        - name: "druid.coordinator.startDelay"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "string"
      defaultValues:
        - fromVersion: "0.0.0"
          value: "PT20S"
      roles:
        - name: "broker"
          required: false
        - name: "coordinator"
          required: true
        - name: "historical"
          required: false
        - name: "middleManager"
          required: false
        - name: "router"
          required: false
      asOfVersion: "0.0.0"

  - property: &indexerQueueStartDelay
      propertyNames:
        - name: "druid.indexer.queue.startDelay"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "string"
      defaultValues:
        - fromVersion: "0.0.0"
          value: "PT20S"
      roles:
        - name: "broker"
          required: false
        - name: "coordinator"
          required: true
        - name: "historical"
          required: false
        - name: "middleManager"
          required: false
        - name: "router"
          required: false
      asOfVersion: "0.0.0"

  - property: &indexerRunnerType
      propertyNames:
        - name: "druid.indexer.runner.type"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "string"
      defaultValues:
        - fromVersion: "0.0.0"
          value: "remote"
      roles:
        - name: "broker"
          required: false
        - name: "coordinator"
          required: true
        - name: "historical"
          required: false
        - name: "middleManager"
          required: false
        - name: "router"
          required: false
      asOfVersion: "0.0.0"

  - property: &indexerStorageType
      propertyNames:
        - name: "druid.indexer.storage.type"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "string"
      defaultValues:
        - fromVersion: "0.0.0"
          value: "metadata"
      roles:
        - name: "broker"
          required: false
        - name: "coordinator"
          required: true
        - name: "historical"
          required: false
        - name: "middleManager"
          required: false
        - name: "router"
          required: false
      asOfVersion: "0.0.0"

  - property: &coordinatorPeriod
      propertyNames:
        - name: "druid.coordinator.period"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "string"
      defaultValues:
        - fromVersion: "0.0.0"
          value: "PT20S"
      roles:
        - name: "broker"
          required: false
        - name: "coordinator"
          required: true
        - name: "historical"
          required: false
        - name: "middleManager"
          required: false
        - name: "router"
          required: false
      asOfVersion: "0.0.0"

  - property: &coordinatorAsOverlordEnabled
      propertyNames:
        - name: "druid.coordinator.asOverlord.enabled"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "bool"
      defaultValues:
        - fromVersion: "0.0.0"
          value: "true"
      roles:
        - name: "broker"
          required: false
        - name: "coordinator"
          required: true
        - name: "historical"
          required: false
        - name: "middleManager"
          required: false
        - name: "router"
          required: false
      asOfVersion: "0.0.0"

  - property: &segmentCacheLocations
      propertyNames:
        - name: "druid.segmentCache.locations"
          kind:
            type: "file"
            file: "runtime.properties"
      datatype:
        type: "string"
      defaultValues:
        - fromVersion: "0.0.0"
          value: "[{\"path\":\"/stackable/var/druid/segment-cache\",\"maxSize\":\"300g\"}]"
      roles:
        - name: "broker"
          required: false
        - name: "coordinator"
          required: false
        - name: "historical"
          required: true
        - name: "middleManager"
          required: false
        - name: "router"
          required: false
      asOfVersion: "0.0.0"

###################################################################################################
# jvm.config
###################################################################################################

###################################################################################################
# log.properties
###################################################################################################

  - property: &ioTrino
      propertyNames:
        - name: "io.trino"
          kind:
            type: "file"
            file: "log.properties"
      datatype:
        type: "string"
      defaultValues:
        - fromVersion: "0.0.0"
          value: "INFO"
      allowedValues:
        - "INFO"
        - "DEBUG"
        - "WARN"
        - "ERROR"          
      roles:
        - name: "coordinator"
          required: true
        - name: "worker"
          required: true
      asOfVersion: "0.0.0"
