= Usage

Druid requires a Zookeeper to run, as well as a database.


== Setup Prerequisites

=== Zookeeper operator

Please refer to the https://github.com/stackabletech/zookeeper-operator[Zookeeper] operator and https://docs.stackable.tech/zookeeper/index.html[docs].

=== SQL Database

Druid requires a MySQL or Postgres database.

For testing purposes, you can spin up a PostgreSQL database with the bitnami PostgreSQL helm chart.  Add the bitname repository:

    helm repo add bitnami https://charts.bitnami.com/bitnami

And setup the Postgres database:

    helm install druid bitnami/postgresql \
    --set postgresqlUsername=druid \
    --set postgresqlPassword=druid \
    --set postgresqlDatabase=druid

=== Creating a Druid Cluster

With the prerequisites fulfilled, the CRD for this operator must be created:

    kubectl apply -f /etc/stackable/druid-operator/crd

Then a cluster can be deployed. Fill in the correct database connection and deep storage configuration.  For the deep storage configuration using local storage, a node should be labeled and selected in the configuration, here the label `nodeType=druid-data` is used. On this node at the path given in `storageDirectory` the data will be stored.

    cat <<EOF | kubectl apply -f -
apiVersion: druid.stackable.tech/v1alpha1
kind: DruidCluster
metadata:
  name: simple
spec:
  version: 0.22.0
  zookeeperReference:
    namespace: default
    name: simple
  metadataStorageDatabase:
    dbType: postgresql
    connString: jdbc:postgresql://druid-postgresql/druid
    host: druid-postgresql
    port: 5432
    user: druid
    password: druid
  deepStorage:
    storageType: local
    dataNodeSelector:
      nodeType: druid-data
    storageDirectory: /path/to/druidDeepStorage
  brokers:
    roleGroups:
      default:
        config:
          plaintextPort: 8082
        replicas: 1
  coordinators:
    roleGroups:
      default:
        config:
          plaintextPort: 8081
        replicas: 1
  historicals:
    roleGroups:
      default:
        config:
          plaintextPort: 8083
        replicas: 1
  middleManagers:
    roleGroups:
      default:
        config:
          plaintextPort: 8091
        replicas: 1
  routers:
    roleGroups:
      default:
        config:
          plaintextPort: 8888
        replicas: 1

The Router is hosting the web UI, to be able to access the web interface you need to forward port 8888 first:

         kubectl port-forward --namespace default po/<router-pod-name> 8888:8888

Now open `http://localhost:8888` in your browser and follow the https://druid.apache.org/docs/latest/tutorials/index.html#step-4-load-data[druid documentation] on how to load and query sample data.