---
apiVersion: v2
name: druid-operator
version: 0.6.0-nightly
appVersion: "0.6.0-nightly"
description: The Stackable Operator for Apache Druid
home: https://github.com/stackabletech/druid-operator
maintainers:
  - name: Stackable
    url: https://www.stackable.tech
