apiVersion: druid.stackable.tech/v1alpha1
kind: DruidCluster
metadata:
  name: simple
spec:
  version: 0.22.0
  brokers:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: stackable-linux
        replicas: 1
  coordinators:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: stackable-linux
        replicas: 1
  historicals:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: stackable-linux
        replicas: 1
  middlemanagers:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: stackable-linux
        replicas: 1
  routers:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: stackable-linux
        replicas: 1