[package]
authors = ["Stackable GmbH <info@stackable.de>"]
description = "Contains the druid CRD structs and utilities"
edition = "2021"
license = "OSL-3.0"
name = "stackable-druid-crd"
repository = "https://github.com/stackabletech/druid-operator"
version = "0.3.0-nightly"

[dependencies]
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", tag = "0.7.0" }

duplicate = "0.3.0"
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = "0.23"
strum_macros = "0.23"
thiserror = "1.0"
tracing = "0.1"

[dev-dependencies]
indoc = "1.0"
rstest = "0.12"
serde_yaml = "0.8"
