[package]
authors = ["Lars Francke <lars.francke@stackable.de>"]
description = "Contains the druid CRD structs and utilities"
edition = "2018"
license = "OSL-3.0"
name = "stackable-druid-crd"
repository = "https://github.com/stackabletech/druid-operator"
version = "0.1.0"

[dependencies]
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", tag = "0.4.0" }
stackable-zookeeper-crd = { git = "https://github.com/stackabletech/zookeeper-operator.git", branch = "adapt_to_use_docker_image" }

duplicate = "0.3.0"
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = "0.21"
strum_macros = "0.21"
thiserror = "1.0"
tracing = "0.1"

[dev-dependencies]
indoc = "1.0"
rstest = "0.11"
serde_yaml = "0.8"

[features]
# default = ["native-tls"]
# native-tls = ["kube/native-tls"]
# rustls-tls = ["kube/rustls-tls"]
