= Installation

On this page you will install the Stackable Druid Operator, the Stackable ZooKeeper Operator - a dependency of Druid - as well as a third-party PostgreSQL Operator.

== Stackable Operators

There are 2 ways to run Stackable Operators

1. Using xref:stackablectl::index.adoc[]

1. Using Helm

=== stackablectl

stackablectl is the command line tool to interact with Stackable operators and our recommended way to install Operators.
Follow the xref:stackablectl::installation.adoc[installation steps] for your platform.

After the installation run to install the Apache Druid Operator:

[source,bash]
----
include::example$code/getting-started.sh[tag=stackablectl-install-operators]
----

The tool will show

----
[INFO ] Installing commons operator
[INFO ] Installing secret operator
[INFO ] Installing zookeeper operator
[INFO ] Installing druid operator
----

TIP: Consult the xref:stackablectl::quickstart.adoc[] to learn more about how to use stackablectl.

=== Helm

You can also use Helm to install the Operators. Add the Stackable Helm repository:
[source,bash]
----
include::example$code/getting-started.sh[tag=helm-add-repo]
----

Then install the Stackable Operator for Apache Druid
[source,bash]
----
include::example$code/getting-started.sh[tag=helm-install-operators]
----

Helm will deploy the operator in a Kubernetes container and apply the CRDs for the Apache Druid service. You are now ready to deploy Apache Druid in Kubernetes.


== PostgreSQL dependency

Druid requires a MySQL or Postgres database.

For your first Druid instance, use the bitnami PostgreSQL Helm Chart. Add the bitnami Helm repository:

[source,bash]
----
include::example$code/getting-started.sh[tag=add-helm-bitnami-repo]
----

== What's next

xref:first_cluster.adoc[Set up a Druid cluster].