= Stackable Operator for Apache Druid

This is an operator for Kubernetes that can manage https://druid.apache.org/[Apache Druid] clusters. Dive right in with the xref:druid:getting_started/index.adoc[Getting Started guide].

Installing the Operator also installs the _DruidCluster_ CustomResourceDefinition. The DruidCluster definition supports 5 xref:home:concepts:roles-and-role-groups.adoc[roles]: **Router**, **Coordinator**, **Broker**, **MiddleManager** and **Historical**.
The roles correspond to https://druid.apache.org/docs/latest/design/processes.html[Druid processes].

== Resources

Below you can see the resources created by the Operator for a given DruidCluster.

image::druid_overview.drawio.svg[]

The operator creates:

* A StatefulSet for each RoleGroup
** Each StatefulSet then spawns one or more Pods
*** Pods containing ...? (Monitoring? xref:concepts:logging.adoc[]?)
* A ConfigMap for each RoleGroup containing
** a log configuration file
** JVM configuration file
** The runtime.properties file
* A xref:discovery.adoc[discovery ConfigMap] which contains information on how to connect to the Druid cluster.
* Services for each Role as well as RoleGroup.

(Service Accounts?)


If a DruidCluster is deleted, the ConfigMaps are retained (?)


== Dependencies and Other Operators to connect to

The Druid Operator has the following dependencies:

* The xref:commons-operator:index.adoc[] provides common CRDs such as xref:concepts:s3.adoc[] CRDs.
* The xref:secret-operator:index.adoc[] is required for things like S3 access credentials or LDAP integration.
* Apache ZooKeeper via the xref:zookeeper:index.adoc[]. Apache ZooKeeper is used by Druid for internal communication between processes.
* A storage backend. Either HDFS with the xref:hdfs:index.adoc[] or S3. (TODO: link to S3 deep storage config usage)

You can ingest data from Kafka with the xref:kafka:index.adoc[].

Trino with the xref:trino:index.adoc[] can read from Druid.

OPA with the xref:opa:index.adoc[] for Authorization.

== Demos

xref:stackablectl::index.adoc[] supports installing xref:stackablectl::demos/index.adoc[] which showcase multiple components of the Stackable platform working together. These two demos include Druid as part of the data pipeline:

=== Waterlevel Demo

The xref:stackablectl::demos/nifi-kafka-druid-water-level-data.adoc[] demo uses data from https://www.pegelonline.wsv.de/webservice/ueberblick[PEGELONLINE] to visualize water levels in rivers and coastal regions of Germany from historic and real time data.

=== Earthquake Demo

The xref:stackablectl::demos/nifi-kafka-druid-earthquake-data.adoc[] demo ...


== Supported Versions

The Stackable Operator for Apache Druid currently supports the following versions of Druid:

include::partial$supported-versions.adoc[]
