---
apiVersion: v1
data:
  properties.yaml: |
    ---
    
kind: ConfigMap
metadata:
  name: druid-operator-configmap
  labels:
    app.kubernetes.io/name: druid-operator
    app.kubernetes.io/instance: druid-operator
    app.kubernetes.io/version: "23.4.0"
