= Druid extensions
:druid-extensions: https://druid.apache.org/docs/latest/configuration/extensions/
:druid-core-extensions: https://druid.apache.org/docs/latest/configuration/extensions/#core-extensions
:druid-community-extensions: https://druid.apache.org/docs/latest/configuration/extensions/#loading-community-extensions
:description: Add functionality to Druid with default or custom extensions. Default extensions include Kafka and HDFS support; community extensions require extra setup.

{druid-extensions}[Druid extensions] are used to provide additional functionality at runtime, e.g. for data formats or different types of deep storage.

== [[default-extensions]]Default extensions

Druid Stacklets use the following extensions by default:

* `druid-kafka-indexing-service`
* `druid-datasketches`
* `prometheus-emitter`
* `druid-basic-security`
* `druid-opa-authorizer`
* `druid-hdfs-storage`

Some extensions are loaded conditionally depending on the DruidCluster configuration:

* `postgresql-metadata-storage` (when using PostgreSQL as metadata store)
* `mysql-metadata-storage` (when using MySQL as metadata store)
* `druid-s3-extensions` (when S3 is used as deep storage)
* `simple-client-sslcontext` (when TLS is enabled)

== [[custom-extensions]]Custom extensions

You can configure Druid to load more extensions by adding them to the `additionalExtensions` list as shown below:

[source,yaml]
----
spec:
  clusterConfig:
    additionalExtenions:
    - druid-avro-extensions
    - druid-google-extensions
    ...
----

{druid-core-extensions}[Core extensions] are already bundled with Druid but adding community extensions requires {druid-community-extensions}[some extra steps].

Some extensions may require additional configuration which can be added using xref:usage-guide/overrides.adoc[configuration and environment overrides].
