= Storage and resource configuration
:description: Configure storage and resource requests for Druid with default settings for CPU, memory, and additional settings for historical segment caches.

== Storage for data volumes

Druid uses S3 or HDFS for deep storage, so no extra https://kubernetes.io/docs/concepts/storage/persistent-volumes[PersistentVolumeClaims] have to be specified.

== Resource Requests

include::home:concepts:stackable_resource_requests.adoc[]

A minimal HA setup consisting of 2 Pods of each role has the following https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/[resource requirements]:

* `4700m` CPU request
* `13800m` CPU limit
* `12144Mi` memory request and limit

Of course, additional services require additional resources.
For Stackable components, see the corresponding documentation on further resource requirements.

Corresponding to the values above, the operator uses the following resource defaults:

[source,yaml]
----
spec:
  brokers:
    config:
      resources:
        cpu:
          min: 100m
          max: 400m
        memory:
          limit: 1500Mi
  routers:
    config:
      resources:
        cpu:
          min: 100m
          max: 400m
        memory:
          limit: 512Mi
  historical:
    config:
      resources:
        cpu:
          min: 300m
          max: 1200m
        memory:
          limit: 1500Mi
  middleManagers:
    config:
      resources:
        cpu:
          min: 300m
          max: 1200m
        memory:
          limit: 1500Mi
  coordinators:
    config:
      resources:
        cpu:
          min: 100m
          max: 400m
        memory:
          limit: 768Mi
----

The operator may configure an additional container for log aggregation.
This is done when log aggregation is configured as described in xref:concepts:logging.adoc[].
The resources for this container cannot be configured using the mechanism described above.
Use xref:concepts:overrides.adoc#_pod_overrides[podOverrides] for this purpose.

You can configure your own resource requests and limits by following the example above.

== Historical Resources

In addition to the cpu and memory resources described above, historical Pods also accept a `storage` resource with the following properties:

* `segmentCache` - used to set the maximum size allowed for the historical segment cache locations.
   See the Druid documentation regarding https://druid.apache.org/docs/latest/configuration/index.html#historical[druid.segmentCache.locations].
   The operator creates an `emptyDir` and sets the `max_size` of the volume to be the value of the `capacity` property.
   In addition Druid is configured to keep 7% volume size free.
   By default, if no `segmentCache` is configured, the operator creates an `emptyDir` with a size of `1G` and `freePercentage` of `5`.

Example historical configuration with storage resources:

[source,yaml]
----
historicals:
  roleGroups:
    default:
      config:
        resources:
          storage:
            segmentCache:
              # The amount of free space to subtract from the capacity setting below. Defaults to 5%
              freePercentage: 7
              emptyDir:
                # The maximum size of the volume used to store the segment cache
                capacity: 2Gi
----
